// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/outstanding": {
    params: {};
  };
  "/customers": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/purchases": {
    params: {};
  };
  "/suppliers": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/stocks": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/sales": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/outstanding" | "/customers" | "/dashboard" | "/purchases" | "/suppliers" | "/products" | "/register" | "/settings" | "/reports" | "/stocks" | "/login" | "/sales" | "/users" | "/*";
  };
  "routes/[outstanding]._index.jsx": {
    id: "routes/[outstanding]._index";
    page: "/outstanding";
  };
  "routes/[customers]._index.jsx": {
    id: "routes/[customers]._index";
    page: "/customers";
  };
  "routes/[dashboard]._index.jsx": {
    id: "routes/[dashboard]._index";
    page: "/dashboard";
  };
  "routes/[purchases]._index.jsx": {
    id: "routes/[purchases]._index";
    page: "/purchases";
  };
  "routes/[suppliers]._index.jsx": {
    id: "routes/[suppliers]._index";
    page: "/suppliers";
  };
  "routes/[products]._index.jsx": {
    id: "routes/[products]._index";
    page: "/products";
  };
  "routes/[register]._index.jsx": {
    id: "routes/[register]._index";
    page: "/register";
  };
  "routes/[settings]._index.jsx": {
    id: "routes/[settings]._index";
    page: "/settings";
  };
  "routes/[reports]._index.jsx": {
    id: "routes/[reports]._index";
    page: "/reports";
  };
  "routes/[stocks]._index.jsx": {
    id: "routes/[stocks]._index";
    page: "/stocks";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/[sales]._index.jsx": {
    id: "routes/[sales]._index";
    page: "/sales";
  };
  "routes/[users]._index.jsx": {
    id: "routes/[users]._index";
    page: "/users";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[outstanding]._index": typeof import("./app/routes/[outstanding]._index.jsx");
  "routes/[customers]._index": typeof import("./app/routes/[customers]._index.jsx");
  "routes/[dashboard]._index": typeof import("./app/routes/[dashboard]._index.jsx");
  "routes/[purchases]._index": typeof import("./app/routes/[purchases]._index.jsx");
  "routes/[suppliers]._index": typeof import("./app/routes/[suppliers]._index.jsx");
  "routes/[products]._index": typeof import("./app/routes/[products]._index.jsx");
  "routes/[register]._index": typeof import("./app/routes/[register]._index.jsx");
  "routes/[settings]._index": typeof import("./app/routes/[settings]._index.jsx");
  "routes/[reports]._index": typeof import("./app/routes/[reports]._index.jsx");
  "routes/[stocks]._index": typeof import("./app/routes/[stocks]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/[sales]._index": typeof import("./app/routes/[sales]._index.jsx");
  "routes/[users]._index": typeof import("./app/routes/[users]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};